
version: '3.0'
services:
  web:
    image: "mnabywaniec/io-lab-docker-public:latest"
    build : 
        context: .
  
    ports:
        - "5000:5000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:6.0-rc3
    volumes: 
         - ./data:/data

